#pragma once
#include <local.SPINORExecuteOpcode_req.h>
#include <local.SPINORExecuteOpcode_res.h>

#define LOCAL_SPINOREXECUTEOPCODE_ID 210
#define LOCAL_SPINOREXECUTEOPCODE_SIGNATURE (0x52D1E06453399CA1ULL)

#if defined(__cplusplus) && defined(DRONECAN_CXX_WRAPPERS)
#include <canard/cxx_wrappers.h>
SERVICE_MESSAGE_CXX_IFACE(local_SPINORExecuteOpcode, LOCAL_SPINOREXECUTEOPCODE_ID, LOCAL_SPINOREXECUTEOPCODE_SIGNATURE, LOCAL_SPINOREXECUTEOPCODE_REQUEST_MAX_SIZE, LOCAL_SPINOREXECUTEOPCODE_RESPONSE_MAX_SIZE);
#endif
